version: '3'
services:
  ddac:
    image: "datastax/ddac"
    container_name: "ddac"
    environment:
       - DS_LICENSE=accept
    ports:
      - "9042:9042"
  ddb-cassandra-proxy:
    build: ./ 
    container_name: "ddb-cas-proxy"
    command: |
      java -Ddw.contactPoints="ddac" -jar /opt/cql-cassandra-proxy/cql-cassandra-proxy-0.1.0.jar server /opt/cql-cassandra-proxy/cql-cassandra-proxy.yaml
    ports:
      - "8080:8080"
    depends_on:
      - ddac
    restart: unless-stopped
